server:
  port: 8087

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/assignment
    username: username
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

    hikari:
      maximum-pool-size: 4

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        use_sql_comments: true